### ISSUE TITLE
configuration for --up and --up-restart

### ISSUE THREAD

**Issue by vielmetti** [daschatten/openvpn-formula#3]
Motivated by https://github.com/saltstack/salt/issues/22124 I am looking at ways to use openvpn-formula to drive restarts of salt-minion on clients when the vpn network comes up after being down (perhaps being down for an extended period of time).

This is designed to work around the problem in particular where salt minions become unreachable even though the network is up.

**Comment by daschatten** [comment]
Sorry for let you waiting. I added a new option '_append' in which you can place all options not directly supported. Please have a look in pillar.example.
Does this suite your needs?

**Comment by vielmetti** [comment]
Ah, I see this commit https://github.com/daschatten/openvpn-formula/commit/f7fd71c500244d549d8a87e9b2cda568c8e0673b and I'll give it a try next time I'm building a system. Thanks for the help.

**Comment by daschatten** [comment]
Thank you!
